### ISSUE TITLE
[BUG] couldn't get hostname for AWS endpoint

### ISSUE THREAD

**Issue by Lance-Kraakman** [FreeRTOS/iot-reference-esp32c3#23]
**Describe the bug**
When I try to run the example, after i provision the device i get a 'couldnt get hostname' error. 

**System information**
- Hardware board: (tried on custom board and  ESP32-C3-DevKitC-02)
- IDE used: visual studio code w/ esp-idf plugin 
- ESP_IDF version: 4.4.3
- Operating System: Windows
- Code version: (run ``git describe --tags`` to find it)
- Project/Demo: default 

**Expected behavior**
The device connects to mqtt broker.

**Screenshots or console output**
I (112490) core_mqtt_agent_manager: WiFi connected.
I (112490) app_wifi: Connected with IP Address:192.168.1.91
I (112490) esp_netif_handlers: sta ip: 192.168.1.91, mask: 255.255.255.0, gw: 192.168.1.254
I (112500) wifi_prov_mgr: STA Got IP
I (112500) app_wifi: Provisioning successful
I (112510) ota_over_mqtt_demo:  Received: 0   Queued: 0   Processed: 0   Dropped: 0
E (112540) esp-tls: couldn't get hostname for :arn:aws:iot:ap-southeast-2:****:thing/thing2: getaddrinfo() returns 202, addrinfo=0x0
E (112540) esp-tls: Failed to open new connection
I (112860) core_mqtt_agent_manager: Retry attempt 1.
E (112860) esp-tls: couldn't get hostname for :arn:aws:iot:ap-southeast-2:*****:thing/thing2: getaddrinfo() returns 202, addrinfo=0x0
E (112860) esp-tls: Failed to open new connection
I (113320) core_mqtt_agent_manager: Retry attempt 2.

**Steps to reproduce bug**
    Example:
      1. "I am using project iot-reference-project"

CONFIG_GRI_QUALIFICATION_FORCE_GENERATE_NEW_KEY_PAIR is not set
CONFIG_GRI_QUALIFICATION_MQTT_ENDPOINT="arn:aws:iot:ap-southeast-2:12345678912:thing/thing2"
CONFIG_GRI_QUALIFICATION_MQTT_PORT=8883
CONFIG_GRI_QUALIFICATION_CLIENT_IDENTIFIER="PLACE_HOLDER"
CONFIG_GRI_QUALIFICATION_NETWORK_BUFFER_SIZE=5000
CONFIG_GRI_QUALIFICATION_PROCESS_LOOP_TIMEOUT_MS=700
CONFIG_GRI_QUALIFICATION_ECHO_SERVER="PLACE_HOLDER"
CONFIG_GRI_QUALIFICATION_ECHO_SERVER_PORT=9000
CONFIG_GRI_QUALIFICATION_OTA_PAL_CERTIFICATE_FILE=""
CONFIG_GRI_QUALIFICATION_OTA_PAL_FIRMWARE_FILE="/"

CONFIG_GRI_MQTT_ENDPOINT="arn:aws:iot:ap-southeast-2:*****:thing/thing2"
CONFIG_GRI_MQTT_PORT=8883
CONFIG_GRI_THING_NAME="thing2"
CONFIG_GRI_OUTPUT_CERTS_KEYS=y

**Comment by archigup** [comment]
Hey, the MQTT_ ENDPOINT has the wrong value. That should be the AWS IoT Core device data endpoint.

You can get the endpoint by going to https://us-west-2.console.aws.amazon.com/iot/home?region=us-west-2#/settings (and change to correct region). On the IoT Core settings page, the first section has the endpoint URL.

**Comment by Lance-Kraakman** [comment]
Thanks for the quick reply and help, sorry about that.
