### ISSUE TITLE
[Feature Request] Update on planned support for latest ESP-AWS-IoT, ESP-IDF v5.0, and IDF Eclipse Plugin v2.7

### ISSUE THREAD

**Issue by JBHunterI** [FreeRTOS/iot-reference-esp32c3#27]
**Is your feature request related to an issue you've encountered? If so, please elaborate.**
I would simply like to know what is happening with the "plan to update to this IoT Reference to support ESP-IDF v5.0 before, or by Jan end [2023]" mentioned in #16 before it was closed on 2023/12/16.

**Describe the new feature request**
See same section in issue #16.

**Describe other alternatives you've considered**
See same section in issue #16. Currently encountering debug issues with getting this project to use GDB breakpoints with current ESP-IDF v4.4 release branch (v4.4.3).

**Additional context**
There's no mention of ESP-IDF v5.0 in your Forum, my original issue #16 was closed (can't add a new comment), so I felt I had no other choice but to open a new issue.

**Comment by n9wxu** [comment]
PR #20 provides IDF5 support.  it is currently in draft and is being worked on by Espressif.  The best date I can give is "real soon now".  If you pull that PR you can start looking at what it includes and provide comments about any changes you may need.
