### ISSUE TITLE
[BUG] MAX_NUM_OTA_DATA_BUFFERS is missing from the KConfig

### ISSUE THREAD

**Issue by wreyford** [FreeRTOS/iot-reference-esp32c3#98]
MAX_NUM_OTA_DATA_BUFFERS, is missing in the KConfig.projbuild
The project thus fails to build. 

I see that it was set to 8 in the default Config file ie. sdkconfig.defaults. 
So somewhere along the line it was deprecated or removed.

**Comment by ActoryOu** [comment]
Hi @wreyford,
Could you help re-compile with https://github.com/FreeRTOS/iot-reference-esp32c3/pull/99? I fixed the issue locally, but I'd like to have your result with the change.

Thank you.

**Comment by ActoryOu** [comment]
This issue should be resolved by #99. I'm closing it.
Feel free to reopen if it's not resolved with your finding.

Thank you.
